FROM apache/airflow:2.9.1

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

COPY pyproject.toml poetry.lock /opt/airflow/

RUN pip install --no-cache-dir sodapy pandas boto3 psycopg[binary]